### ISSUE TITLE
Wfdisc calib default value should be 1, not -1

### ISSUE THREAD

**Issue by jkmacc-LANL** [jkmacc-LANL/pisces#13]
In `pisces sac2db`, for example, an unset SAC `calib` value should not become a `Wfdisc.calib` value of -1.  That will result in a polarity reversal, if multiplied into the data.  A better value would be 1.  There is no NA value in the schema for `Wfdisc.calib`, and they need to be greater than 0.

**Comment by g2e** [comment]
The KBCORE schema defines the calib default as 1 while CSS3 does not as you mentioned.  So it makes sense to use 1 for the CSS3 default.  pisces.kbcore defines the default calib as -1 so that is also a bug.
