### ISSUE TITLE
Python 3+ support

### ISSUE THREAD

**Issue by Keowne** [jkmacc-LANL/pisces#21]
Hi there,

First off I should say that I have been fine using Pisces v 0.2.1 on OSX with Python 2.7.13 to convert various data to CSS format.

Recently I installed Anaconda which by default uses Python 3.6.2, as well as Pisces (v 0.2.4), ObsPy, SQLAlchemy, and NumPy. Trying to run the same file conversion script I'd been using with Python 2.7.13/Pisces 0.2.1 led to a few errors:

1) In pisces/util.py, on line 508 the "print str(e)" is not formatted for Python 3+ (needs parentheses), i.e., print(str(e))

2a) Fixing #1, leads to an issue in "readwaveform.py", where "from StringIO import StringIO" no longer is valid in Python 3+. This was replaced by importing StringIO or BytesIO from io.

2b) If either io.StringIO or io.BytesIO are used (not sure which is best? i get the same results either way), this then leads to:

~/anaconda3/lib/python3.6/site-packages/pisces/schema/util.py in __init__(cls, clsname, parents, dct)
    367 
    368         # store Column info dictionary in base._column_info_registry
--> 369         for key, val in dct.iteritems():
    370             if isinstance(val, sa.Column):
    371                 try:

AttributeError: 'dict' object has no attribute 'iteritems'

I believe "iteritems" became just "items" in Python 3.

Think that's about it so far.

Thanks!

**Comment by jkmacc-LANL** [comment]
Hi @Keowne.  Pisces has a Python 3 branch I've been working on with colleagues locally that fixes the errors you've outlined.  It's close to being done, but not quite done yet.  This would be a Python 3 only branch; that would be OK with you?

**Comment by Keowne** [comment]
Sounds good. Might be worth clarifying in the various documentation pages what the situation is. Thanks.

**Comment by jkmacc-LANL** [comment]
@Keowne I will clarify this; thank you for your patience.  FYI, I've got a working Python 3 branch, and I'm almost ready to push it to GitHub.  I just wanted to let you know in case you were still waiting for this.

**Comment by Keowne** [comment]
Thanks for the update. No huge rush, am making do with the existing version for now.

**Comment by iceseismic** [comment]
Absolutely fine with me ;   I’m using pisces a lot on a day-to-day level

cheers
stephen

**Comment by jkmacc-LANL** [comment]
This has been pushed!  Thanks for your patience.  Please let me know if there are any problems.
