### ISSUE TITLE
Calibration value formatting in wfdisc file

### ISSUE THREAD

**Issue by Keowne** [jkmacc-LANL/pisces#24]
Hi there,

Not a major issue, but had a query regarding the number format for the calib value field in the wfdisc files. So in css3.py and kbcore.py, calib is defined as follows:

calib = Column(Float(24), 
        info={'default': -1.0, 'parse': parse_float, 'dtype': 'float', 'width': 16, 'format': '16.6f'})

This indicates to me that the calibration value written to the wfdisc file will have a maximum of 6 digits after the decimal point. (I imagine this specification follows from CSS standards.)

However, the calibration value I'm trying to write is on the order of 4e-9 (m/s)/count. Consequently by default, this number gets written as 0.000000, regardless of how it's stored in memory. To address this, is there any harm in me changing the calib format to say 6.16f in the two scripts indicated? I'm not sure if there are any other places where I would potentially need to change this.

Many thanks.

**Comment by jkmacc-LANL** [comment]
Hi, sorry I missed this until now.  The spec calls for calib to be in nanometers.   Would converting fix your issue?

**Comment by jkmacc-LANL** [comment]
Off hand, I don’t think this will affect anything to mod your local code, but it’ll get squashed if you update.
