### ISSUE TITLE
How I can use Pisces with Obspy?

### ISSUE THREAD

**Issue by HAMAMA-SAN** [jkmacc-LANL/pisces#30]
Dear sir,

Kindly can you send me the instructions of using pisces with obspy in reading CSS "wfdisc"format

**Comment by jkmacc-LANL** [comment]
Hi, @HAMAMA-SAN .  If this is related to [your recent ObsPy Issue](https://github.com/obspy/obspy/issues/2387#issuecomment-489891058) about reading waveforms from text "wfdisc" files, it looks like you'll need to do the following:

```python
from pisces.schema.css3 import Wfdisc

with open("myfile.wfdisc", 'r') as wfdisc:
    for row in wfdisc:
        wf = Wfdisc.from_string(row)
        tr = wf.to_trace()
        # tr is an ObsPy trace.  you can do things with it here.

```

`Wfdisc` is a [SQLAlchemy](https://docs.sqlalchemy.org/en/13/orm/) class that represents a SQL table named `wfdisc`, and `wf` is an instance of that class (row in a database).

**Comment by HAMAMA-SAN** [comment]
Yes . This is related to the old issue about reading CSS files. sorry for late reply.
I tried this solution and I got this error 
AttributeError: type object 'Wfdisc' has no attribute '__table_

Many Thanks for your help

**Comment by jkmacc-LANL** [comment]
Ah, I made a mistake in the code!  I’m so sorry. The import statement should be `from pisces.tables.css3 import Wfdisc` .  I will try to edit it in my comment soon.

**Comment by HAMAMA-SAN** [comment]
It works but I got this error 
ValueError: could not convert string to float: '        18-APR-18', column lddate: '        18-APR-18', positions [266:283]

**Comment by jkmacc-LANL** [comment]
It didn't like your `lddate` format.  Can I ask how the file was written (what software was used)?

**Comment by HAMAMA-SAN** [comment]
Really I don't know the software which was used in written this data ... but this is archived data for international data center

**Comment by jkmacc-LANL** [comment]
I think this `lddate` issue is related to #23 .  The current workaround is to use a the column default value when reading the line.  The new snippet would look like this:

```python
from pisces.tables.css3 import Wfdisc

with open("myfile.wfdisc", 'r') as wfdisc:
    for row in wfdisc:
        wf = Wfdisc.from_string(row, default_on_error=['lddate']) 
        # the lddate field will have a null value, which is OK because you're dropping it when you create the Trace object
        tr = wf.to_trace()
        # tr is an ObsPy trace.  you can do things with it here.
```

**Comment by HAMAMA-SAN** [comment]
That's great ...Thanks a lot for your help and support.
It works with me .

**Comment by jkmacc-LANL** [comment]
👍 Thanks for your patience!
