### ISSUE TITLE
problem with "if phase" in get_arrivals ; "phase" not defined

### ISSUE THREAD

**Issue by iceseismic** [jkmacc-LANL/pisces#7]
arrival_query = req.get_arrivals(session, Arrival, assoc=Assoc, stations=[stat], orids=[orid])
  File "/usr/lib64/python2.7/site-packages/pisces/request.py", line 439, in get_arrivals
    if phase:
NameError: global name 'phase' is not defined

**Comment by jkmacc-LANL** [comment]
The line "if phase" should be "if phases". Im away from a computer this week, but I'll fix it when I return or you can make the change yourself in the meantime.

**Comment by jkmacc-LANL** [comment]
Turns out, I can edit the code from my phone:-)

**Comment by iceseismic** [comment]
hi,

many thanks ; 

I think pisces is a great addition to the  obspy-related tools -  thanks 
very much for your development work !!

Most of my legacy datasets are in css3 - its very useful to move from css3 
 to obspy  easily ; and then use 
sqlalchemy ;  although I am still learning the sql queries - using  your 
SRL  article and docs as examples; 

cheers
Stephen 

-----------------------------------------------------------------------------------------------------

Stephen Bannister
GNS Science,  Po Box 30 368, Lower Hutt 5040, New Zealand
+64 4 570 4678 |  s.bannister@gns.cri.nz |  
www.gns.cri.nz/who/staff/1335.html
www.mendeley.com/profiles/stephen-bannister/

**Comment by jkmacc-LANL** [comment]
Stephen,

I'm so happy Pisces is useful for you.  Please feel free to let me know of any issues, and I'll try my best to help as quickly as I can.

Best,
Jonathan


________________________________
