### ISSUE TITLE
mismatch between  util.py  and sqlalchemy ? 

### ISSUE THREAD

**Issue by iceseismic** [jkmacc-LANL/pisces#8]
Hi,
I'm hitting a small error -  could well be my own issue - I'm unsure : 

Traceback (most recent call last):
  File "form_sqldb_from_db.py", line 48, in <module>
    class Site(css.Site):
  File "/sp/prj/tvz95/mypython2/lib64/python2.7/site-packages/pisces_db-0.2.1-py2.7-linux-x86_64.egg/pisces/schema/util.py", line 456, in __init__
    cls._attrname = {c.name: a for a,c in cls.__mapper__.c.items()} #{col_name: attr_name}
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/_collections.py", line 106, in __getattr__
    raise AttributeError(key)
AttributeError: items

where on line 48 of form_sqldb_from_db.py I have :
```python
class Site(css.Site):
    __tablename__ = 'site'
```

Any ideas ?   Some kind of mismatch between  util.py  and  sqlalchemy ??
Any suggestions very welcome 

Stephen

**Comment by jkmacc-LANL** [comment]
Hmmm, this feels like an error I've seen before.  Could you show your imports?

**Comment by iceseismic** [comment]
Trimmed down 5-line version below still results in the same error :   my sqlalchemy version is 0.7.9  so that may be an issue perhaps ?  

#!/usr/bin python 

import sqlalchemy 
import pisces.schema.css3 as css

class Site(css.Site):
    __tablename__ = 'site'

**Comment by iceseismic** [comment]
Note : the above cut & paste didnt capture the "__tablename__"  correctly :   

![code_snapshot](https://cloud.githubusercontent.com/assets/831424/11080532/7adc34b8-8879-11e5-992d-42223577d3e0.JPG)

**Comment by jkmacc-LANL** [comment]
To protect your code block, try using 3 backticks before and after you code, like:
\`\`\`
code here
\`\`\`
I've reformatted your posts like this.

So, I've been able to recreate your error with sqlalchemy 0.7.9, and it went away with sqlalchemy 1.0.9.  This is an error in my `setup.py` file.  I'll correct that.  It should be resolved when you upgrade SQLAlchemy.

**Comment by iceseismic** [comment]
Many thanks for following this up ;  very much appreciated  !

**Comment by jkmacc-LANL** [comment]
My pleasure.  Thanks for giving Pisces a try!
